name: Java Selenium CI

# Trigger on push/pull request to phase_1 and allow manual trigger
on:
  push:
    branches: [ phase_1 ]
  pull_request:
    branches: [ phase_1 ]
  workflow_dispatch:   # manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Navigate to project subdirectory
      - name: Navigate to automation subdirectory
        working-directory: automation-java-framework  # replace with your subfolder

      # Step 4: Build project with Maven
      - name: Build project
        run: mvn clean install

      # Step 5: Run Selenium TestNG tests
      - name: Run TestNG tests
        run: mvn test

      # Step 6: Upload TestNG reports
      - name: Upload TestNG reports
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: automation-java-framework/target/surefire-reports/
